### ISSUE TITLE
Two queries please

### ISSUE THREAD

**Issue by shonilchi** [KelvinCrag/Optimizer#1]
1.  Can I schedule this command via Tasker to have this script run every X number of hours? - Please confirm if this period run is actually necessary.
2. Should I run this ADB command every time I reboot the phone?

**Comment by KelvinCrag** [comment]
Yes, it can be easily scheduled, but it's very unnecessary.

You can just run it after sometime without specific intervals.

OR

As earlier mentioned after a dirty flash or after updating phone.

**Comment by KelvinCrag** [comment]
I created a magisk module that autorun this script anytime you reboot your device which improved device overall performance but it tampered with device boot time :(
