### ISSUE TITLE
Error while using in Ladb

### ISSUE THREAD

**Issue by Pranith-Jain** [KelvinCrag/Optimizer#2]
![Screenshot_20220108-164243](https://user-images.githubusercontent.com/87193560/148642552-513672b0-17fd-4261-be9e-e4e0cfa1c170.jpg)
 I am getting this error when I run in Ladb using wireless debugging .

**Comment by KelvinCrag** [comment]
Type command without "adb shell" at beginning when using Local ADB.

E.g `cmd package bg-dexopt-job`

**Comment by KelvinCrag** [comment]
> ![Screenshot_20220108-164243](https://user-images.githubusercontent.com/87193560/148642552-513672b0-17fd-4261-be9e-e4e0cfa1c170.jpg) I am getting this error when I run in Ladb using wireless debugging .

Also:
![Screenshot_20220109-142952_Pixel Launcher~2](https://user-images.githubusercontent.com/64832927/148684286-6bef1a2e-da55-4a59-bc98-225eac1571d6.png)

**Comment by Pranith-Jain** [comment]
Thanks
