### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by kou9221** [KelvinCrag/Optimizer#4]
What does this thing actually do? Does this delete some unnecessary files to optimize the phone or what? I do want to try this but im afraid i might lose some files

**Comment by kou9221** [comment]
Anyway im using a custom rom and is android 12L is this compatible or not?

**Comment by KelvinCrag** [comment]
It should be compatible for any android version.

https://android.googlesource.com/platform/frameworks/base.git/+/f7edab63d9358b9a4e0dbec3243f6db9f50a2bbe

PS: I'll recommend you read through the [FAQ](https://github.com/KelvinCrag/Optimizer#faq)
