### ISSUE TITLE
notification not showing in status bar

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [KelvinCrag/Optimizer#5]
Hey, I'd like to know the command to be used for fixing the notifications not showing in the status bar. Thanks. Do reply asap.

**Comment by KelvinCrag** [comment]
- Command-line for fix delayed incoming messages issue:
```
> su
> cd /data/data
> find . -type f -name '*gms*' -delete
```

**Comment by KelvinCrag** [comment]
Note: Not related to script.
