### ISSUE TITLE
do you know how to reverse it? i do

### ISSUE THREAD

**Issue by Boy656** [KelvinCrag/Optimizer#7]
for reverse the process use this command su -c "pm compile -r first-boot -f -a" what this command do 
in android 7 and up after format data and install a new application or update your system when you use it first time after install you will notice some heat because you are using the application on verify compiler and after update your system will work on the first time with verify as default compiler for collection and create profile-speed on your phone to be able to use your phone very smoothly but this command will return verify compiler and of course maybe will face some heat looks like you did it a format data or updating your phone without losing your data but if you wanna do optimazer again its work automatically or you will force it with su -c "pm compile -r bg-dexopt" or su -c "bg-dexopt-job"

**Comment by Android4Eva** [comment]
I tried to run this command on compiler:

C:\platform-tools>abd shell pm compile -r first boot -f -a
Error: No compiler filter for reason 'first'

I want to reverse/disable the optimizer on my phone, what am I doing wrong?
